from .prompts import (
    INTERVIEW_QUESTIONS_PROMPT,
    JOB_ANALYSIS_PROMPT,
    RESUME_PARSING_PROMPT,
    SKILL_MATCHING_PROMPT,
)

__all__ = [
    "JOB_ANALYSIS_PROMPT",
    "RESUME_PARSING_PROMPT",
    "SKILL_MATCHING_PROMPT",
    "INTERVIEW_QUESTIONS_PROMPT",
]
